### ISSUE TITLE
publish 1.123.225-2.0.0 to npm

### ISSUE THREAD

**Issue by clncln1** [Dynatrace/agent-nodejs#26]
Hi,

could you please publish (given QA is finished) the current version 1.123.225-2.0.0 to the npm repo?
The currently deployed one (1.123.225-1.0.0) doesn't work in our environment since we have a build system w/o direct internet connectivity and therefore the url dependency cannot be fetched.

Thanks,
Nico

**Comment by danielkhan** [comment]
1.125 is available in npm meanwhile.
